### PR TITLE
ඞ Epic ඞ Improvements ඞ

### PR DESCRIPTION
**Pull request by BeauTheBeau**
i did the epic improvements!!!!!!!!!!!!!!!!!!!! ඞ ඞ ඞ ඞ ඞ ඞ ඞ 

- **Automated credits.html** - `getContributor.js` makes requests to the GitHub API to gather all contributors. Results are also _cached,_ to minimise the amount of requests sent in the case of the visitor refreshing the page. 
- **Reduced border transparency** of the cards in `credits.html` (or `.coolboi`.
- **`.bois` now uses grid**
- Changed visual appearance of the `.coolboi` elements, with the user's profile picture being the background.
image
- Files were also moved to different locations (new `/css`, `/img/` and `/js` directories.
- **Navbar and footer** can now be automatically created

### CODE REVIEW

**Review by LeOptix — COMMENTED** [review]
Looks sus to me 👍

**Comment by BeauTheBeau** [comment]
Ready now :)

**Comment by BeauTheBeau** [comment]
I lied  ඞ

**Review by LeOptix — APPROVED** [review]
sus.

**Comment by BeauTheBeau** [comment]
epic ඞ ඞ ඞ ඞ ඞ

**Pull request merged**
